### Sign IN with credencials

POST http://localhost:3000/api/signin
content-type: application/json

{
    "email": "elton.vilanculo@vae.co.mz",
    "password": "12345678"
}


### Sign UP with credencials
POST http://localhost:3000/api/signup
content-type: application/json

{
    "email": "elton.vilanculo@vae.co.mz",
    "name": "elton",
    "password": "12345678"
}
